### ISSUE TITLE
404 on downloads

### ISSUE THREAD

**Issue by nightah** [thealetheia/broccoli#14]
Seems when trying to run a go generate utilising this library that the following error is returned:

`go: aletheia.icu/broccoli/fs@v0.0.0-20200420200651-c5ac961a357a: unrecognized import path "aletheia.icu/broccoli/fs": reading https://aletheia.icu/broccoli/fs?go-get=1: 404 Not Found`

I can see that https://aletheia.icu is still functional but seems the path for the library isn't working as intended.

**Comment by montanaflynn** [comment]
Tagging @demget @1gm @godande, any update on this? Seems like issues and PRs are unanswered, is this project dead?
